site_name: Perfect Media Server
repo_url: https://github.com/IronicBadger/pms-wiki
repo_name: ironicbadger/pms-wiki
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: overrides
  language: en
  #logo: images/site/logo.png
  favicon: images/assets/favicon.png
  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/regular/folder-open
  palette:
    - scheme: default
      primary: blue
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    code: Jet Brains Mono
  features:
    - navigation.instant
    - navigation.sections # prevents collapsible sections
    - navigation.indexes # section index pages
    - navigation.expand #expands sections by default
  # insiders only
  #   - search.suggest

plugins:
  - git-revision-date
  - search
  - minify:
      minify_html: true
markdown_extensions:
  - abbr
  - admonition # enables coloured blocks mid article
  - attr_list # improves image handling
  - pymdownx.details # enables collapsible admonitions
  - footnotes
  - meta # adds support for front matter
  - toc:
      permalink: true
      toc_depth: 4
  - pymdownx.highlight: # code highlighting
      linenums: true
  - pymdownx.tabbed # enables tabs for embedded blocks
  - pymdownx.snippets
  - pymdownx.superfences # allows for the nesting of code blocks inside other blocks
  - pymdownx.keys

copyright: 2020 - 2022 &copy; Alex Kretzschmar - Licensed under GPLv3
extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/ironicbadger'
      name: IronicBadger on GitHub
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/ironicbadger'
      name: IronicBadger on Twitter
    - icon: 'fontawesome/brands/linkedin'
      link: 'https://www.linkedin.com/in/alex-kretzschmar/'      
    - icon: 'fontawesome/solid/microphone'
      link: 'https://selfhosted.show/'
      name: IronicBadger's Podcast - selfhosted.show
  analytics:
    provider: plausible
    property: pmswiki

nav:
  #- Welcome: 'index.md'
  - 1. Overview:
    - index.md
    - Introduction: '01-overview/overview.md'
    - FAQ: '01-overview/faq.md'
    - NAS Software Comparison: '01-overview/nas-software-comparison.md'
  - 2. Tech Stack Explained:
    - Linux: 'tech-stack/linux.md'
    - Containers:
      - Docker: 'tech-stack/docker.md'
      - docker-compose: 'tech-stack/docker-compose.md'
    - MergerFS: 'tech-stack/mergerfs.md'
    - SnapRAID: 'tech-stack/snapraid.md'
    - ZFS: 'tech-stack/zfs.md'
    - Proxmox: 'tech-stack/proxmox.md'
  - 3. Installation:
    - Manual Install on Ubuntu: 'installation/manual-install-ubuntu.md'
    #- Manual Install on Proxmox: 'installation/manual-install-proxmox.md'
    - Manual Install (Video): 'installation/manual-install-on-video.md'
    - Automated Install: 'installation/automated-install.md'
  - 4. Remote Access: 
    - remote-access/index.md
    - VPNs: 'remote-access/vpns.md'
    - Traefik 101 Guide: 'remote-access/traefik101.md'
    - SSH (Secure Shell): 'remote-access/ssh.md'
    #- WireGuard: 'remote-access/wireguard.md'
  - 5. Hardware:
    - Cases: 'hardware/cases.md'
    - HDD Purchase Methodology: 'hardware/hdd-purchase-methodology.md'
    - New Drive Burn-In Rituals: 'hardware/new-drive-burnin.md'
    #- Post Install Checklist: 'installation/post-install-checklist.md'
  - 6. Day Two (Post Install):
    - Top 10 Self-Hosted Apps: 'day-two/top10apps.md'
    - Backups: 'day-two/backups.md'
    - Quality of Life Tweaks: 'day-two/quality-of-life-tweaks.md'
  - 7. Advanced:
    - Concepts:
      - Infrastructure as Code: 'concepts/infraascode.md'
      - Hypervisors: 'concepts/hypervisors.md'
      - PCI Passthrough: 'concepts/pci-passthrough.md'
    - Configuration:
      - Using ZFS with MergerFS: 'advanced/combine-zfs-and-others.md'
      - Quick Sync and Proxmox passthrough: 'advanced/passthrough-igpu-gvtg.md'
  #- Related Projects:
    #- Virtualised OPNsense router: 'related-projects/virtualised-opnsense-proxmox.md'
