name: Deploy to VPS via Tailscale

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-via-tailscale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3

      - name: Connect Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          # Tailscale version to use.
          version: '1.46.1'

      # Build
      - name: Pull latest changes on VPS
        uses: appleboy/ssh-action@master
        with:
            host: ktz-cloud
            username: ${{ secrets.VPS_DEPLOY_USER }}
            script: cd ${{ secrets.VPS_PROJECT_PATH }} && git pull
            
      - name: Build on VPS
        uses: appleboy/ssh-action@master
        with:
            host: ktz-cloud
            username: ${{ secrets.VPS_DEPLOY_USER }}
            script: cd ${{ secrets.VPS_PROJECT_PATH }} && docker-compose run pms-wiki build
